
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sample6?createDatabaseIfNotExist=true
    username: root
    password: 5680288
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop

